
from building import *

cwd     = GetCurrentDir()
src     = Glob('src/*.c')
CPPPATH = [cwd + '/inc', cwd + '/samples/porting']  # 添加两个不同的路径

if GetDepend(['FAL_USING_SFUD_PORT']):
    src += Glob('samples/porting/fal_flash_sfud_port.c')

group = DefineGroup('Fal', src, depend = ['RT_USING_FAL'], CPPPATH = CPPPATH)

Return('group')
